/**
 * Catálogo Curado de Fundos de Previdência Privada Brasileira
 * Dados de referência pública (ANBIMA / SUSEP / Entidades Abertas)
 * 
 * Entidades representadas:
 * - Brasilprev (Banco do Brasil)
 * - Bradesco Vida e Previdência
 * - Itaú Previdência
 * - Icatu Seguros
 * - XP Vida e Previdência
 * - BTG Pactual Vida e Previdência
 * - SulAmérica Previdência
 */

export type PrevidenciaRiskProfile = 'conservative' | 'moderate' | 'aggressive';

export interface PrevidenciaFund {
  id: string;
  name: string;
  institution: string;
  profile: PrevidenciaRiskProfile;
  categoryLabel: string;
  benchmark: string;
  managementFeePct: number;
  loadingFeePct: number; // taxa de carregamento (0% padrão moderno)
  expectedAnnualReturnPct: number; // Projeção anual média de longo prazo líquida (%)
  return12mPct: number; // Histórico recente 12m (%)
  return36mPct: number; // Histórico 36m (%)
  volatilityAnnualPct: number;
  minInitialInvestmentBRL: number;
  description: string;
  equityAllocationMaxPct: number; // Limite de ações CVM 175
}

export const PREVIDENCIA_FUNDS_CATALOG: PrevidenciaFund[] = [
  // ─── PERFIL CONSERVADOR (Renda Fixa / Pós-fixado DI / Tesouro Selic) ─────────
  {
    id: 'xp_horizonte_rf',
    name: 'XP Horizonte FIC Renda Fixa Previdenciário',
    institution: 'XP Vida e Previdência',
    profile: 'conservative',
    categoryLabel: 'Renda Fixa DI Soberano',
    benchmark: '100% CDI',
    managementFeePct: 0.40,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 10.5,
    return12mPct: 10.45,
    return36mPct: 35.80,
    volatilityAnnualPct: 0.18,
    minInitialInvestmentBRL: 100,
    description: 'Fundo soberano pós-fixado alocado majoritariamente em títulos públicos federais (LFT/Tesouro Selic). Máxima segurança e liquidez para preservação de capital.',
    equityAllocationMaxPct: 0,
  },
  {
    id: 'brasilprev_fix',
    name: 'Brasilprev Fix FIC Renda Fixa Previdenciário',
    institution: 'Brasilprev / Banco do Brasil',
    profile: 'conservative',
    categoryLabel: 'Renda Fixa Pós-Fixada',
    benchmark: '98% CDI',
    managementFeePct: 0.50,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 10.2,
    return12mPct: 10.25,
    return36mPct: 34.60,
    volatilityAnnualPct: 0.25,
    minInitialInvestmentBRL: 200,
    description: 'Gestão conservadora pela BB DTVM com foco em títulos públicos federais e ativos bancários de baixo risco. Ideal para aposentadoria a curto/médio prazo.',
    equityAllocationMaxPct: 0,
  },
  {
    id: 'btg_tesouro_selic_prev',
    name: 'BTG Pactual Tesouro Selic Simples Prev FIC RF',
    institution: 'BTG Pactual Vida e Previdência',
    profile: 'conservative',
    categoryLabel: 'Renda Fixa Soberana Taxa Zero',
    benchmark: '100% CDI',
    managementFeePct: 0.25,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 10.6,
    return12mPct: 10.55,
    return36mPct: 36.10,
    volatilityAnnualPct: 0.12,
    minInitialInvestmentBRL: 100,
    description: 'Uma das menores taxas de administração do mercado para previdência privada (0,25%). 100% alocado em títulos públicos federais com risco soberano mínimo.',
    equityAllocationMaxPct: 0,
  },
  {
    id: 'itau_private_di_prev',
    name: 'Itaú Previdência Private DI FIC Renda Fixa',
    institution: 'Itaú Previdência',
    profile: 'conservative',
    categoryLabel: 'Renda Fixa DI Ativa',
    benchmark: '100% CDI',
    managementFeePct: 0.45,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 10.4,
    return12mPct: 10.35,
    return36mPct: 35.10,
    volatilityAnnualPct: 0.22,
    minInitialInvestmentBRL: 500,
    description: 'Estratégia sólida com carteira diversificada em títulos pós-fixados públicos e privados bancários de primeira linha (AAA).',
    equityAllocationMaxPct: 0,
  },
  {
    id: 'bradesco_fic_rf_prev',
    name: 'Bradesco PGBL/VGBL FIC Renda Fixa Clássico',
    institution: 'Bradesco Vida e Previdência',
    profile: 'conservative',
    categoryLabel: 'Renda Fixa Tradicional',
    benchmark: '98% CDI',
    managementFeePct: 0.60,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 10.1,
    return12mPct: 10.10,
    return36mPct: 34.20,
    volatilityAnnualPct: 0.28,
    minInitialInvestmentBRL: 250,
    description: 'Fundo clássico gerido pela BRAM (Bradesco Asset Management) com alta liquidez e foco em papéis com risco soberano e bancário primário.',
    equityAllocationMaxPct: 0,
  },

  // ─── PERFIL MODERADO (Crédito Privado / Inflação IMA-B / Multimercado) ────────
  {
    id: 'icatu_vanguarda_inflacao',
    name: 'Icatu Vanguarda Previdência Inflação Curta FIC FI',
    institution: 'Icatu Seguros',
    profile: 'moderate',
    categoryLabel: 'Renda Fixa Inflação (IMA-B 5)',
    benchmark: 'IPCA + 5,8% / IMA-B 5',
    managementFeePct: 0.70,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 11.8,
    return12mPct: 12.10,
    return36mPct: 40.50,
    volatilityAnnualPct: 2.80,
    minInitialInvestmentBRL: 500,
    description: 'Proteção direta contra a inflação via títulos do Tesouro IPCA+ com vencimentos até 5 anos (menor oscilação de marcação a mercado). Garante ganho real de capital.',
    equityAllocationMaxPct: 0,
  },
  {
    id: 'itau_personnalite_imab_prev',
    name: 'Itaú Personnalité Previdência IMA-B FIC RF',
    institution: 'Itaú Previdência',
    profile: 'moderate',
    categoryLabel: 'Renda Fixa Títulos Públicos IPCA',
    benchmark: 'IMA-B Geral',
    managementFeePct: 0.75,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 12.2,
    return12mPct: 12.80,
    return36mPct: 42.10,
    volatilityAnnualPct: 4.50,
    minInitialInvestmentBRL: 1000,
    description: 'Replica a cesta de títulos do Tesouro IPCA+ de todos os vencimentos. Ideal para quem busca retornos expressivos acima da inflação para aposentadorias de 5 a 15 anos.',
    equityAllocationMaxPct: 0,
  },
  {
    id: 'xp_seguros_alocacao_moderada',
    name: 'XP Seguros Alocação Moderada FIC FIM Prev',
    institution: 'XP Vida e Previdência',
    profile: 'moderate',
    categoryLabel: 'Multimercado Balanceado',
    benchmark: 'CDI + 2,0% a.a.',
    managementFeePct: 0.90,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 12.5,
    return12mPct: 12.60,
    return36mPct: 43.40,
    volatilityAnnualPct: 3.40,
    minInitialInvestmentBRL: 500,
    description: 'Gestão ativa multiestratégia combinando títulos atrelados à inflação (60%), crédito privado de alta nota (25%) e até 15% em ações e cotas internacionais.',
    equityAllocationMaxPct: 15,
  },
  {
    id: 'btg_credito_privado_prev',
    name: 'BTG Pactual Crédito Privado Prev FIC FIM',
    institution: 'BTG Pactual Vida e Previdência',
    profile: 'moderate',
    categoryLabel: 'Crédito Privado Corporativo',
    benchmark: '108% CDI',
    managementFeePct: 0.80,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 11.5,
    return12mPct: 11.40,
    return36mPct: 39.20,
    volatilityAnnualPct: 1.10,
    minInitialInvestmentBRL: 500,
    description: 'Investimento em debêntures e títulos de crédito de grandes empresas brasileiras, buscando retorno sistematicamente superior ao CDI com baixa oscilação.',
    equityAllocationMaxPct: 0,
  },
  {
    id: 'sulamerica_prestige_prev',
    name: 'SulAmérica Prestige Multimercado Previdenciário',
    institution: 'SulAmérica Previdência',
    profile: 'moderate',
    categoryLabel: 'Multimercado Macro Balanceado',
    benchmark: 'CDI + 1,5% a.a.',
    managementFeePct: 0.85,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 12.0,
    return12mPct: 11.90,
    return36mPct: 41.00,
    volatilityAnnualPct: 2.90,
    minInitialInvestmentBRL: 500,
    description: 'Tradição da SulAmérica em fundos de pensão com alocação flexível entre juros locais, câmbio e índices de preços.',
    equityAllocationMaxPct: 10,
  },

  // ─── PERFIL AGRESSIVO (Ações / Multimercado Macro Livre CVM 175) ─────────────
  {
    id: 'xp_investor_acoes_prev',
    name: 'XP Investor Dividendos Previdência FIC FIA',
    institution: 'XP Vida e Previdência',
    profile: 'aggressive',
    categoryLabel: 'Ações Dividendos B3',
    benchmark: 'IDIV / Ibovespa',
    managementFeePct: 1.50,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 14.5,
    return12mPct: 15.80,
    return36mPct: 54.20,
    volatilityAnnualPct: 14.20,
    minInitialInvestmentBRL: 500,
    description: 'Foco em empresas brasileiras consolidadas, com histórico recorrente de lucros e pagamento generoso de proventos e dividendos. Perfeito para horizonte acima de 10 anos.',
    equityAllocationMaxPct: 70,
  },
  {
    id: 'brasilprev_acoes_prev',
    name: 'Brasilprev Ações Valor FIC FIA Previdenciário',
    institution: 'Brasilprev / Banco do Brasil',
    profile: 'aggressive',
    categoryLabel: 'Ações B3 Seleção Fundamentalista',
    benchmark: 'Ibovespa',
    managementFeePct: 1.40,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 14.0,
    return12mPct: 14.90,
    return36mPct: 51.30,
    volatilityAnnualPct: 15.50,
    minInitialInvestmentBRL: 200,
    description: 'Gestão da BB Asset focada em companhias líderes em setores perenes da economia brasileira (bancos, energia elétrica, commodities e saneamento).',
    equityAllocationMaxPct: 70,
  },
  {
    id: 'btg_absoluto_acoes_prev',
    name: 'BTG Pactual Absoluto Ações Previdência FIC FIA',
    institution: 'BTG Pactual Vida e Previdência',
    profile: 'aggressive',
    categoryLabel: 'Ações Long Only Alta Performance',
    benchmark: 'Ibovespa + 3% a.a.',
    managementFeePct: 1.60,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 15.5,
    return12mPct: 16.40,
    return36mPct: 58.90,
    volatilityAnnualPct: 16.80,
    minInitialInvestmentBRL: 1000,
    description: 'Espelho da consagrada estratégia BTG Absoluto adaptada às regras de previdência CVM 175. Carteira concentrada nas melhores teses de valor e crescimento da B3.',
    equityAllocationMaxPct: 70,
  },
  {
    id: 'icatu_verde_prev',
    name: 'Icatu Verde Previdência FIC FIM',
    institution: 'Icatu Seguros / Verde Asset',
    profile: 'aggressive',
    categoryLabel: 'Multimercado Macro Global',
    benchmark: 'CDI + 3,5% a.a.',
    managementFeePct: 1.80,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 14.2,
    return12mPct: 14.30,
    return36mPct: 49.80,
    volatilityAnnualPct: 8.50,
    minInitialInvestmentBRL: 1000,
    description: 'Gestão da Verde Asset Management (Luis Stuhlberger) adaptada para previdência privada. Alocação global em juros, câmbio, crédito e bolsa nacional e internacional.',
    equityAllocationMaxPct: 40,
  },
  {
    id: 'spx_nimitz_prev',
    name: 'SPX Nimitz Previdência FIC FIM',
    institution: 'SulAmérica / SPX Capital',
    profile: 'aggressive',
    categoryLabel: 'Multimercado Macro Dinâmico',
    benchmark: 'CDI + 3% a.a.',
    managementFeePct: 1.75,
    loadingFeePct: 0.0,
    expectedAnnualReturnPct: 14.0,
    return12mPct: 13.90,
    return36mPct: 48.20,
    volatilityAnnualPct: 7.80,
    minInitialInvestmentBRL: 1000,
    description: 'Uma das mais renomadas gestoras macro do Brasil (Rogério Xavier) operando mercados de juros, moedas e equities com visão global e proteção de capital.',
    equityAllocationMaxPct: 35,
  },
];
